### ISSUE TITLE
License Tag in Example not valid in current 

### ISSUE THREAD

**Issue by SteveGrehl** [R-Lum/xlum_specification#4]
According to the current XSD 'CC BY 4.0' is not a valid entry for the license tag.

See:

https://github.com/R-Lum/xlum_specification/blob/84e766ebe857fec1b5ffab9839a1cc281afb455b/xsd_schema/xlum_schema.xsd#L219-L231

It is however set in the provided example.

https://github.com/R-Lum/xlum_specification/blob/84e766ebe857fec1b5ffab9839a1cc281afb455b/examples/xlum_example.xlum#L2-L3

Hence it will produce errors such as the following

```
lxml.etree.XMLSyntaxError: Element 'xlum', attribute 'license': [facet 'enumeration'] The value 'CC BY 4.0' is not an element of the set {'CC BY', 'CC BY-SA', 'CC BY-NC', 'CC BY-NC-SA', 'CC BY-ND', 'CC BY-NC-ND', 'CC0', 'Copyright'}.
```

Either add the  'CC BY 4.0' to the license enumeration or adjust the example. Allowing a generic string as a license may be an option too.

**Comment by RLumSK** [comment]
@SteveGrehl Thanks!
